name: TabulaRasa
favicon: null
layout_spectrum: 0.99815
typography_spectrum: 0.6428730853367597
title: A New Beginning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23262f'
    - '#747a76'
    - '#b3bfb5'
    - '#c89279'
    - '#f8fd7b'
  brandStrength: 0.5
  lightness: 0.48272803286090493
  saturation: 0.2333187924232334
  rhythmicContrast: 0.4907561612781137
purpose: []
