name: TabulaRasa
favicon: null
layout_spectrum: 0.6366109137888998
typography_spectrum: 0.6428730853367597
title: A New Beginning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10821169032715261
  lightness: 0.48272803286090493
  saturation: 0.2333187924232334
  rhythmicContrast: 0.4907561612781137
purpose: []
